import io, base64
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
from reportlab.lib.utils import ImageReader

def render_skin_report_pdf(prediction: dict) -> bytes:
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    w, h = A4
    y = h - 2*cm

    c.setFont("Helvetica-Bold", 16)
    c.drawString(2*cm, y, "GlucoLens — Skin Screening Report (Grad-CAM)")
    y -= 0.8*cm
    c.setFont("Helvetica", 10)
    c.drawString(2*cm, y, "Screening support only. Acanthosis is a risk proxy; confirm clinically.")
    y -= 1.0*cm

    probs = prediction.get("probabilities", {})
    c.setFont("Helvetica-Bold", 12); c.drawString(2*cm, y, "Summary"); y -= 0.6*cm
    c.setFont("Helvetica", 11)
    c.drawString(2*cm, y, f"Predicted: {prediction.get('predicted_label')}"); y -= 0.5*cm

    if probs.get("positive") is not None:
        c.drawString(2*cm, y, f"P(positive proxy): {float(probs.get('positive')):.3f}"); y -= 0.6*cm
    else:
        q = prediction.get("quality_gate", {})
        c.drawString(2*cm, y, f"Quality gate failed: {q.get('reason')}"); y -= 0.6*cm

    c.setFont("Helvetica-Bold", 12); c.drawString(2*cm, y, "Grad-CAM Overlay"); y -= 0.6*cm

    overlay_b64 = (prediction.get("explainability") or {}).get("overlay_png_base64")
    if overlay_b64:
        img_bytes = base64.b64decode(overlay_b64.encode("utf-8"))
        img = ImageReader(io.BytesIO(img_bytes))
        c.drawImage(img, 2*cm, y-12*cm, width=14*cm, height=12*cm, preserveAspectRatio=True, mask="auto")
        y -= 12.5*cm
    else:
        c.setFont("Helvetica", 10)
        c.drawString(2*cm, y, "No overlay (retake image / not available).")
        y -= 0.5*cm

    c.setFont("Helvetica-Oblique", 9)
    c.drawString(2*cm, 2*cm, "Generated by GlucoLens • Skin explainability via Grad-CAM.")
    c.showPage(); c.save()
    return buf.getvalue()