import io, base64
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
from reportlab.lib.utils import ImageReader

def render_retina_report_pdf(*, prediction: dict) -> bytes:
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    w, h = A4
    y = h - 2*cm

    c.setFont("Helvetica-Bold", 16)
    c.drawString(2*cm, y, "GlucoLens — Retina Screening Report")
    y -= 0.8*cm

    c.setFont("Helvetica", 10)
    c.drawString(2*cm, y, "Screening support only. Confirm with clinical evaluation and labs.")
    y -= 1.0*cm

    probs = prediction.get("probabilities", {})
    c.setFont("Helvetica-Bold", 12)
    c.drawString(2*cm, y, "Prediction Summary")
    y -= 0.6*cm
    c.setFont("Helvetica", 11)
    c.drawString(2*cm, y, f"Predicted label: {prediction.get('predicted_label')}")
    y -= 0.5*cm
    c.drawString(2*cm, y, f"P(not diabetic): {probs.get('not_diabetic',0):.3f}")
    y -= 0.5*cm
    c.drawString(2*cm, y, f"P(T2D/positive proxy): {probs.get('t2d',0):.3f}")
    y -= 0.8*cm

    c.setFont("Helvetica-Bold", 12)
    c.drawString(2*cm, y, "Grad-CAM Overlay")
    y -= 0.6*cm

    overlay_b64 = (prediction.get("explainability") or {}).get("overlay_png_base64")
    if overlay_b64:
        img_bytes = base64.b64decode(overlay_b64.encode("utf-8"))
        img = ImageReader(io.BytesIO(img_bytes))
        # draw 14cm wide
        c.drawImage(img, 2*cm, y-12*cm, width=14*cm, height=12*cm, preserveAspectRatio=True, mask="auto")
        y -= 12.5*cm
    else:
        c.setFont("Helvetica", 10)
        c.drawString(2*cm, y, "No Grad-CAM available.")
        y -= 0.5*cm

    c.setFont("Helvetica-Oblique", 9)
    c.drawString(2*cm, 2*cm, "Generated by GlucoLens • Retina explainability via Grad-CAM.")
    c.showPage()
    c.save()
    return buf.getvalue()