import io
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm

def render_external_validation_pdf(*, title: str, dataset_meta: dict, model_meta: dict, metrics: dict) -> bytes:
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    w, h = A4

    y = h - 2*cm
    c.setFont("Helvetica-Bold", 16)
    c.drawString(2*cm, y, title)
    y -= 0.9*cm

    c.setFont("Helvetica", 10)
    c.drawString(2*cm, y, "External validation on real site data (de-identified). Screening support only.")
    y -= 1.0*cm

    c.setFont("Helvetica-Bold", 12)
    c.drawString(2*cm, y, "Dataset")
    y -= 0.6*cm
    c.setFont("Helvetica", 10)
    for k in ["site_name", "country_code", "n_rows", "sha256"]:
        if y < 2.5*cm:
            c.showPage(); y = h - 2*cm
        c.drawString(2*cm, y, f"{k}: {dataset_meta.get(k)}")
        y -= 0.45*cm

    y -= 0.3*cm
    c.setFont("Helvetica-Bold", 12)
    c.drawString(2*cm, y, "Model")
    y -= 0.6*cm
    c.setFont("Helvetica", 10)
    c.drawString(2*cm, y, f"model_name: {model_meta.get('model_name')}")
    y -= 0.45*cm
    c.drawString(2*cm, y, f"model_version: {model_meta.get('model_version')}")
    y -= 0.8*cm

    c.setFont("Helvetica-Bold", 12)
    c.drawString(2*cm, y, "Metrics")
    y -= 0.6*cm
    c.setFont("Helvetica", 10)

    lines = [
        f"n: {metrics.get('n')}",
        f"positive_rate: {metrics.get('positive_rate'):.3f}",
        f"AUROC: {metrics.get('auroc') if metrics.get('auroc') is not None else 'N/A'}",
        f"AUPRC: {metrics.get('auprc') if metrics.get('auprc') is not None else 'N/A'}",
        f"Brier: {metrics.get('brier'):.4f}",
        f"ECE: {metrics.get('ece'):.4f}",
        f"Calibration slope: {metrics.get('cal_slope'):.3f}",
        f"Calibration intercept: {metrics.get('cal_intercept'):.3f}",
        f"Log loss: {metrics.get('log_loss'):.4f}",
    ]

    ci = metrics.get("auroc_delong_95ci")
    if ci:
        lines.insert(3, f"AUROC 95% CI (DeLong): {ci.get('ci_low'):.3f}–{ci.get('ci_high'):.3f}")

    for ln in lines:
        if y < 2.5*cm:
            c.showPage(); y = h - 2*cm
            c.setFont("Helvetica", 10)
        c.drawString(2*cm, y, ln)
        y -= 0.45*cm

    y -= 0.4*cm
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(2*cm, 2*cm, "Generated by GlucoLens • Keep audit logs and hashes for integrity & compliance.")

    c.showPage()
    c.save()
    return buf.getvalue()